config/routes.rb
Rails.application.routes.draw do

  resources :urgencies
  root 'pages#home'

  # DASHBOARD
  get '/admins/dashboard', to: 'admins#dashboard'
  get '/trades/dashboard', to: 'trades#dashboard'
  get '/users/dashboard', to: 'users#dashboard'     ## dashboard_path
  post '/users/edit', to: 'users#edit'      ## users_edit_path
  post '/trades/edit', to: 'trades#update'
  post '/admins/edit', to: 'admins#update'


  #QUOTES
  get '/client_quotes', to: 'quotes#client_quotes'
  get '/supplier_quotes', to: 'quotes#supplier_quotes'


  #delete '/booking/:id', to: 'bookings#destroy'
  #get '/users/:id', to: 'users#show'
  #need to review this because its stopping access to user sign_in and user sign_up  , but not sure why ???
  #stopped temporarily 27.Sep.2019



  #OFFERS
  get '/offer_bookings/:id', to: 'offers#bookings', as: 'offer_bookings'
  post '/offers/:id', to: 'offers#show'
  get '/all_offers', to: 'offers#list'
  post '/offers/new', to: 'offers#create'


  ## BOOKINGS
  get '/my_bookings', to: 'bookings#my_bookings'
  get '/bookings/:id', to: 'bookings#show'
  post '/bookings', to: 'bookings#create'
  post '/booking/new', to: 'bookings#create'
  put '/bookings/:id/edit', to: 'bookings#edit'
  put '/bookings/:id/withdraw', to: 'bookings#withdraw'
  put '/bookings/:id', to: 'bookings#withdraw'
  put '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  put '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'
  get '/my_bookings', to: 'bookings#my_bookings'
  get '/bookings/:id', to: 'bookings#show'

  #REVIEWS
  post '/reviews', to: 'reviews#create'


  #LISTINGS
  get '/listings/client_listings', to: 'listings#client_listings' #listings_client_listings_path ???

  #devise_for :admins
  #devise_for :users, path: 'users'
  #devise_for :trades, path: 'trades'
  #devise_for :admins, path: 'admins'

  #get 'users/show'
  #get 'trades/show'
  #get 'admins/show'

# Devise for Users

  authenticated :users do
    # root to:'users/sessions#new', as: :authenticated_user_root
    # root to: 'users/users#dashboard', as: :authenticated_user_root
  end


  devise_for :users, path: 'users', controllers: {
      #sessions: 'users/sessions',
      # stopped calling sessions controller temporarily 21.09.19
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    path_names: {
      sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'
    }

    devise_scope :users do
      get 'sign_up', :to => 'users/registrations#new'
      get 'sign_in', :to => 'users/sessions#new'
      delete 'signout', :to => 'users/sessions#destroy'
    end


    # Devise for Traders

      authenticated :trades do
       #root to:'trades/sessions#new', as: :authenticated_trade_root
       root to: 'trades/trades#dashboard', as: :authenticated_trade_root
      end


      devise_for :trades, path: 'trades', controllers: {
          sessions: 'trades/sessions',
          # stopped calling sessions controller temporarily 21.09.19
          registrations: 'trades/registrations',
          passwords: 'trades/passwords',
          confirmations: 'trades/confirmations',
          #omniauth_callbacks: 'trades/omniauth_callbacks'
        },
        path_names: {
          sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'
        }

        devise_scope :trades do
          get 'signup', :to => 'trades/registrations#new'
          get 'signin', :to => 'trades/sessions#new'
          delete 'signout', :to => 'trades/sessions#destroy'
        end

# Devise for Admins

    authenticated :admins do
      root to: 'admins/sessions#new' , as: :authenticated_admin_root
    end


    devise_for :admins, path: 'admins', controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        confirmations: 'admins/confirmations'
      }

    devise_scope :admins do
      get 'signup', :to => 'admins/registrations#new'
      get 'signin', :to => 'admins/sessions#new'
      delete 'signout', :to => 'admins/sessions#destroy'
    end

    #devise_for :users
    #  devise_scope :user do
    #  get '/users/sign_out' => 'devise/sessions#destroy'
    #end


  # resources :users, except: [:new]

  resources :users do
    #resources :address do
      resources :address_homes, controller: :address, type: 'Home'
      resources :address_business, controller: :address, type: 'Business'
      resources :address_jobs, controller: :address, type: 'Job'
      resources :address_pickups, controller: :address, type: 'PickUp'
      resources :address_dropoffs, controller: :address, type: 'DropOff'
      resources :contacts, controller: :contact
    #end
  end


  resources :trades, except: [:new]
  resources :admins, except: [:new]
  resources :categories, except: [:destroy]
  resources :sections, except: [:destroy]
  resources :pricings, except: [:destroy]
  resources :offers
  resources :bookings
  resources :after_register
  resources :after_address

  resources :listings do
    member do
      delete :delete_photo
      post :upload_photo
    end
    #resources :listing_pricings
    resources :quotes, only: [:create]      #listings/15/quotes
  end

  #resources :listing_pricings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'

end

app/models/listing.rb
class Listing < ApplicationRecord

  before_create   :calc_fields

  belongs_to :client, class_name: "User", optional: true
  belongs_to :category, optional: true, foreign_key: "category_id", class_name: "Category"
  belongs_to :urgency

  has_many_attached :photos
  has_rich_text :description

  has_many :quotes

  has_many :reviews

  validates :title, presence: { message: 'cannot be blank' }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end

  def calc_fields
    self.expiry_date = self.created_at  + 1000.days;
  end

  #has_many :pricings
  #accepts_nested_attributes_for :pricings
  #has_many :listing_categories
  #accepts_nested_attributes_for :listing_pricings, allow_destroy: true, reject_if: proc { |att| att['pricing_id'].blank? }

  # has_many :listing_pricings
  # has_many :pricings, through: :listing_pricings

end

app/models/section.rb
class Section < ApplicationRecord

  has_many :category_sections
  has_many :categories, through: :category_sections

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    protect_from_forgery except: [:upload_photo]
    before_action :authenticate_user!, except: [:show]
    before_action :set_listing, except: [:new, :create, :index, :client_listings]
    before_action :set_step, only: [:update, :edit]
    before_action :is_authorised, only: [:edit, :update, :upload_photo, :delete_photo]
    before_action :set_category, only: [:new, :edit, :show]


    def new
        @listing = current_user.listings.build
        @categories = Category.all
        @urgencies = Urgency.all
    end

    def create
      @listing = current_user.listings.build(listing_params)

      if @listing.save
        redirect_to edit_listing_path(@listing), notice: "Saved..."
      else
        redirect_to request.referrer , flash: { error: @listing.errors.full_messages.to_sentence }
      end
    end

    def edit
      @urgencies = Urgency.all

      @listing = Listing.find(params[:id])
      #@category = Category.find(params[:id])

      @listing_category = @listing.category
    end

    def update

      @listing = Listing.find(params[:id])
      #@category = Category.find(params[:id])
      @urgencies = Urgency.all

      if @step == 2
      end

      if @step == 3 && listing_params[:description].blank?
        return redirect_to request.referrer, flash: {error: "Description cannot be blank"}
      end

      if @step == 4 && @listing.photos.blank?
        return redirect_to request.referrer, flash: {error: "You don't have any photos"}
      end

      if @step == 5
            if @listing[:title].blank? || @listing[:urgency_id].blank?
              return redirect_to edit_listing_path(@listing, step: 2), flash: {error: "Invalid pricing"}
      end


        if @listing.description.blank?
          return redirect_to edit_listing_path(@listing, step: 3), flash: {error: "Description cannot be blank"}
        elsif @listing.photos.blank?
          return redirect_to edit_listing_path(@listing, step: 4), flash: {error: "You don't have any photos"}
        end
      end

      if @listing.update(listing_params)
        flash[:notice] = "Saved..."
      else
        return redirect_to request.referrer, flash: {error: @listing.errors.full_messages}
      end

      if @step < 5
        redirect_to edit_listing_path(@listing, step: @step + 1)
      else
        redirect_to users_dashboard_path
      end
    end

    def show
      @listing = Listing.find(params[:id])
      @listing_category = @listing.category
      @urgencies = Urgency.all
    end

    def index
      @listings = Listing.paginate(page: params[:page], per_page: 10)
    end

    def client_listings
      @listings = current_user.listings.paginate(page: params[:page], per_page: 10)
    end

    def upload_photo
      @listing.photos.attach(params[:file])
      render json: { success: true}
    end


    def delete_photo
      @image = ActiveStorage::Attachment.find(params[:photo_id])
      @image.purge
      redirect_to edit_listing_path(@listing, step: 4)
    end

    private

    def set_step
      @step = params[:step].to_i > 0 ? params[:step].to_i : 1
      if @step > 5
        @step = 5
      end
    end

    def set_category
      @categories = Category.all
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You do not have permission" unless current_user.id == @listing.client_id
    end

    def listing_params
        params.require(:listing).permit(:title, :video, :description, :active, :category_id, :budget, :urgency_id, :status, :expiry_date)
    end

    def category_params
      params.require(:category).permit(:name)
    end

  end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= render 'shared/errors', obj: @listing %>
<p>
  <p>

    <%= form_for(@listing, :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class='form-group row'>
        <div class='col-sm-8'>
             <%= f.label :title %>
         </div>
         <div class='col-sm-8 mb-4'>
             <%= f.text_field :title, class: 'form-control', placeholder: 'Listing Category [UPDATED]...', autofocus: true %>
         </div>
       </div>


       <div class='form-group row'>
         <div class='col-sm-8'>
              <%= f.label :title %>
          </div>
          <div class='col-sm-8 mb-4'>
              <%= f.text_field :title, class: 'form-control', placeholder: 'Brief title for your listing...', autofocus: true %>
          </div>
        </div>


        <div class='form-group row'>
          <div class='col-sm-8'>
               <%= f.label :description %>
           </div>
           <div class='col-sm-8 mb-4'>
               <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Description...', autofocus: true %>
           </div>
        </div>


        <div class='form-group row'>
          <div class='col-sm-2 mb-3'>
               <%= f.label :booking_date %>
               <%= f.text_field :booking_date, class: 'form-control', placeholder: 'Date...', autofocus: true %>
           </div>
           <div class='col-sm-2 mb-3 offset-md-1'>
                <%= f.label :budget %>
                <%= f.text_field :budget, class: 'form-control', placeholder: 'Your Budget...', autofocus: true %>
            </div>
            <div class='col-sm-2 mb-3 offset-md-1'>
                 <%= f.label :postcode %>
                 <%= f.text_field :postcode, class: 'form-control', placeholder: 'Your Postcode...', autofocus: true %>
             </div>
        </div>

        <div class='form-group row'>
          <div class="row">
          <div class='col-sm-12'>
            <% Category.all.each do |category| %>
              <%= check_box_tag "listing[category_ids][]", category.id %>
              <%= category.name %><br>
            <% end %>

            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <%= cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>

          </div>
          </div>
        </div>

         <div class='form-group row'>
           <div class='col-sm-8'>
             <%= f.submit class: 'btn btn-primary btn-lg' %>
           </div>
         </div>




 <% end %>

app/views/listings/_listing.html.erb
<% @listings.each do |li| %>
      <div class = "row">
            <div class = "col-12">
                  <div class = "card bg-light mt-4">
                        <h5><div class = "card-header">placeholder</div></h5>
                            <div class = "card-body">
                                <div class = "listing-body">
                                    <div class = "card-title listing-title"><%= link_to li.title, listing_path(li) %></div>
                                    <p><div class = "card-text"><%= li.description %>
                                      <div class="listing-meta-details">
                                        <small>Created by:  <%= li.client.username if li.client %>,
                                                            <%= time_ago_in_words(li.created_at) %> ago,
                                            last updated:   <%= time_ago_in_words(li.updated_at) %> ago
                                        </small>
                                      </div>
                                    </div>
                                    <p><h5><%= li.budget %></h5>

  <% if li.category.present? %>
    <p>Category: <%= render li.category %></p>
  <% end %>


  <% if ( user_signed_in? && current_user == li.client ) || current_admin %>

      <div class="listing-actions">
      <%= link_to 'Edit this listing', edit_listing_path(li), class: "btn btn-xs btn-primary" %>
      <%= link_to 'Delete this listing', listing_path(li),
      method: :delete, data: { confirm: "Are you sure you want to delete the listing"}, class: "btn btn-xs btn-danger" %>
      </div>
  <% end %>
                                </div>
                          </div>
                  </div>
            </div>
      </div>
<% end %>

app/views/listings/_listing2.html.erb
<section class="section">
  <div class="container-fluid">
    <p class="title">Your Requested Bookings</p>

      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Category</th>
            <th>Created On</th>
            <th>Expires In</th>
            <th>Title</th>
            <th>When Required ?</th>
            <th>Deposit Required</th>
            <th>Verified ?</th>
            <th>Views</th>
            <th>Actions</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% if @listings.blank? %>
              <tr>
                <td colspan="12" class: ><h1>NOTHING TO SHOW HERE</h1><td>
              </tr>
          <% end %>
          <% @listings.each do |l| %>
          <tr>
            <td><%= l.category.name %></td>
            <td><%= l.created_at.strftime('%d %b %Y') %></td>
            <td>
              <div class="countdown-class" data-due-date=<%= l.expiry_date.to_date %> ></div>
            </td>
            <td><%= link_to truncate(l.title, length: 50), listing_path(l) %></td>
            <td><%= l.urgency.name %></td>
            <td>£10</td>
            <td>Yes</td>
            <td>9999</td>
            <td>
              Pending
            </td>
            <td>

              </td>

            <td>

            </td>
          </tr>
          <% if l.expiry_date.to_date - Date.today.to_date <= 1 %>
          <script type="text/javascript">
                $(".countdown-class").each(function() {
                  $(this).countdown($(this).data("due-date"), function(event) {
                    $(this).text(event.strftime('%I hour%!I %M min%!M'));
                  });
                });
          </script>
            <% elsif l.expiry_date.to_date - Date.today.to_date < 7 %>
            <script type="text/javascript">
                $(".countdown-class").each(function() {
                  $(this).countdown($(this).data("due-date"), function(event) {
                    $(this).text(event.strftime('%D day%!D'));
                  });
                });
            </script>
            <% elsif l.expiry_date.to_date - Date.today.to_date < 31 %>
            <script type="text/javascript">
                $(".countdown-class").each(function() {
                  $(this).countdown($(this).data("due-date"), function(event) {
                    $(this).text(event.strftime('%W week%!W'));
                  });
                });
            </script>
            <% elsif l.expiry_date.to_date - Date.today.to_date < 365 %>
            <script type="text/javascript">
                $(".countdown-class").each(function() {
                  $(this).countdown($(this).data("due-date"), function(event) {
                    $(this).text(event.strftime('%m month%!m'));
                  });
                });
            </script>
            <% else %>
            <script type="text/javascript">
            $(".countdown-class").each(function() {
              $(this).countdown($(this).data("due-date"), function(event) {
                $(this).text(event.strftime('%Y year%!Y'));
              });
            });
            </script>
            <% end %>
          <% end %>



        </tbody>
      </table>
  </div>
</section>

app/views/listings/_price_fields.html.erb
<fieldset>









</fieldset>

app/views/listings/_step1.html.erb
<div class="step-content <%= 'is-active' if @step == 1 %>">
        <div class="form-group control col-md-12 mb-4">
          <label class="label">Give Your Job | Listing A Title</label>
          <%= f.text_field :title, autocomplete: "title", class: "form-control input is-focused" %>
        </div>

        <div class="form-group control col-md-12 mb-4">
          <%= f.label :category, 'Pick A Category Most Appropriate' %>
              <div class= 'is-focused field has-addons control is-expanded select is-fullwidth'>
                    <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @listing.category_id)) %>
              </div>
        </div>

        <div class="form-group control col-md-12 mb-4">
          <%= f.label :urgency, 'How Soon Do You Need This Done ' %>
              <div class= 'is-focused field has-addons control is-expanded select is-fullwidth'>
                    <%= f.select(:urgency_id, options_for_select(@urgencies.map{ |c| [c.name, c.id] }, selected: @listing.urgency_id)) %>
              </div>
        </div>

</div>

app/views/listings/_step3.html.erb
<div class="step-content <%= 'is-active' if @step == 3 %>">
    <div class="form-group control col-md-12 mb-4">
      <%= f.label :description, 'Description : ' %>
      <%= f.rich_text_area :description, rows: 50, cols: 50, class: 'input is-focused form-control', type: 'text', placeholder: 'Describe Price Element', autofocus: true , size: "5x5"
      %>
    </div>


    <div class="form-group control col-md-12 mb-4">
      <%= f.label :budget, 'Budget : ' %>
      <%= f.number_field :budget, autocomplete: "budget", class: "form-control input is-focused" %>
    </div>
</div>

app/views/listings/_step4.html.erb
<div class="step-content <%= 'is-active' if @step == 4 %>">

    <div class="field">
        <label for="" class="label">Youtube Code</label>
        <%= f.text_field :video, autocomplete: "video url", class: "input" %>
    </div>

    <div class="field">
      <label for="" class="label">Build Your Listing Gallery</label>
      <div class="control">
        <div class="m-b-20">
          <div class="dropzone" id="myDropZone" action="/listings/<%= @listing.id %>/upload_photo" ></div>
        </div>

        <div class="columns is-multiline" style: width: 100%% >
          <% @listing.photos.each do |photo| %>
            <div class="column is-one-fifth">
              <div class="card is-image">
                <div class="card-image">
                <%= link_to 'Remove', delete_photo_listing_url(photo_id: photo.id , id: @listing.id, step: @step),
                    method: :delete,
                    data: { confirm: "Are you sure ?"},
                    class: "delete delete-file is-pulled-right",
                    style: "z-index: 100" %>

                <figure class="image is-4by3">
                  <%= image_tag url_for(photo) %>
                </figure>
              </div>
            </div>
          </div>

    <% end %>
        </div>
      </div>
  </div>
</div>

<script>
  Dropzone.options.myDropzone = {
    paramName: "file",
    maxFilesize: 2,
    acceptedFiles: "image/*",
    init: function() {
      this.on('complete', function (file) {
        location.reload();
      })
    }
  }
</script>

app/views/listings/_step5.html.erb
<div class="step-content has-text-centered <%= 'is-active' if @step == 5 %>">
  <div>
    <%= hidden_field_tag 'active', 'true' if @step == 5 %>
    <strong class="is-size-2">Almost there...</strong>
    <p>Let's publish your Listing and get your job completed.</p>
  </div>
</div>

<div class="field is-grouped is-grouped-centered m-t-25">
  <p class="control <%= 'is-hidden' if @step <= 1 %>">
    <%= link_to 'Back', edit_listing_path(@listing, step: @step - 1), class: "button is-light" %>
  </p>

  <p class="control">
    <% if @step != 5 %>
      <%= f.submit 'Save & Continue', class: "button is-primary" %>
    <% else %>
      <%= link_to 'Publish', listing_path(@listing.id, listing: {active: true}, step: @step),
                  method: :put,
                  data: {confirm: "Do you want to post your listing ?"},
                  class: "button is-danger" %>
    <% end %>
  </p>
  </div>
</div>

app/views/listings/client_listings.html.erb
<%= render 'listing2', obj: @listings %>


<div class="digg_pagination">
  <div align="center">
      <div class="page_info">
        <%= page_entries_info @listings %>
      </div>
        <%= will_paginate(@listings)  %>
      </div>
</div>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/index.html.erb
<div class="container">
      <h4>Listings</h4>


      <%= render 'listing', obj: @listings %>


          <div class="digg_pagination">
            <div align="center">
                <div class="page_info">
                  <%= page_entries_info @listings %>
                </div>
                  <%= will_paginate(@listings)  %>
                </div>
          </div>
</div>

app/views/listings/new.html.erb
<%= render 'shared/errors', obj: @listing %>

<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item is-active is-primary">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Membership</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW listing HERE-->
      <%= form_for @listing, html: { class: "steps-content m-l-100 m-r-100"} do |f| %>
        <div class="form-group control col-md-12 mb-4">
          <label class="label">Give Your Job | Listing A Title</label>
          <%= f.text_field :title, autocomplete: "title", class: "form-control input is-focused" %>
        </div>

        <div class="form-group control col-md-12 mb-4">
          <%= f.label :category, 'Pick A Category Most Appropriate' %>
              <div class= 'is-focused field has-addons control is-expanded select is-fullwidth'>
                    <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] })) %>
              </div>
        </div>

        <div class="form-group control col-md-12 mb-4">
          <%= f.label :urgency, 'How Soon Do You Need This Done ' %>
              <div class= 'is-focused field has-addons control is-expanded select is-fullwidth'>
                    <%= f.select(:urgency_id, options_for_select(@urgencies.map{ |c| [c.name, c.id] })) %>
              </div>
        </div>

        <div class="field is-grouped is-grouped-centered m-t-25">
          <a href="" class="button is-light">Cancel</a>
          <%= f.submit "Save & Continue", class: "button is-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/listings/show.html.erb
<%= render 'shared/categories' %>

<section class="section">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Listing Detail -->
                  <div class="column is-full">
                    <div class="card">
                      <div class="card-content">
                          <div class="content">
                          <p class="title is-4"><%= @listing.title %></p>
                          </div>
                          <hr>


                            <!-- Start Hero Carousel -->
                            		<section class="hero is-fullheight is-fullwidth">
                            			<div id="carousel-demo" class="hero-carousel">
                                    <% @listing.photos.each do |photo| %>
                                        <div class="has-background image is-16by9">
                                          <%= image_tag url_for(photo), class:"is-background", width:"100%" %>
                                        </div>
                                    <% end %>
                                    <% if @listing.video.present? %>
                                      <div class="video-container">
                                        <iframe src="https://www.youtube.com/embed/<%= @listing.video %>" allowfullscreen></iframe>
                                      </div>
                                    <% end %>
                            			</div>
                            			<div class="hero-head"></div>
                            			<div class="hero-body"></div>
                            			<div class="hero-foot"></div>
                            		</section>
                            		<!-- End Hero Carousel -->

                      </div>
                    </div>
                  </div>

                    <!-- About Section -->
                    <div class="column">
                      <div class="card">
                        <div class="card-content">
                          <article class="media">
                            <div class="media-content">
                              <p><strong>About This Listing</strong></p>
                              <hr>
                              <%= @listing.description %>
                            </div>
                          </article>
                        </div>
                      </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column is-one-third">
              <!-- Pricing Section -->
                <div class="columns is-multiline">
                      <div class="column is-full">

                          <div class="tabs is-fullwidth" id="tabs">
                              <ul>

                              </ul>
                          </div>

                          <div class="tabs-content">



                          </div>

                      </div>
                </div>

                  <!-- Profile Section -->
                <div class="columns is-multiline">

                      <div class="column is-full">
                          <div class="card">
                              <div class="card-content is-horizontal-center is-flex">
                                  <figure class="image is-96x96">
                                      <%= image_tag avatar_url(@listing.client), class: 'is-rounded' %>
                                  </figure>
                              </div>
                              <div class="card-content f-15">
                                  <div class="content has-text-centered">
                                      <p class="title is-5"><%= @listing.client.full_name %></p>
                                      <button class="button is-black is-outlined is-fullwidth">Contact me</button>
                                  </div>
                                  <article class="media">
                                      <div class="media-content">
                                          <i class="fas fa-user m-r-5"></i> Member since
                                      </div>
                                      <div class="media-right">
                                          <%= @listing.client.created_at.strftime('%b %Y') %>
                                      </div>
                                  </article>
                                  <article class="media">
                                      <div class="media-content">
                                          <i class="fas fa-map-marker-alt m-r-5"></i> From
                                      </div>
                                      <div class="media-right">
                                          <%= @listing.client.from %>
                                      </div>
                                  </article>
                                  <article class="media">
                                      <div class="media-content">
                                          <%= @listing.client.about %>
                                      </div>
                                  </article>
                              </div>
                          </div>
                      </div>
                </div>

                </div>
            </div>
</section>


<script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.4/dist/js/bulma-carousel.min.js"></script>
<script>
  bulmaCarousel.attach('#carousel-demo', {
    slidesToScroll: 1,
    slidesToShow: 1
  });

  $(document).ready(function() {
    $('#tabs li').on('click', function() {
       var type = $(this).data('tab');

       $('#tabs li').removeClass('is-active');
       $(this).addClass('is-active');

       $('.tab-content').hide();
       $('#tab-' + type).show();
    })
  })

</script>