config/routes.rb
Rails.application.routes.draw do

  resources :urgencies
  root 'pages#home'

  # DASHBOARD
  get '/admins/dashboard', to: 'admins#dashboard'
  get '/trades/dashboard', to: 'trades#dashboard'
  get '/users/dashboard', to: 'users#dashboard'     ## dashboard_path
  post '/users/edit', to: 'users#edit'      ## users_edit_path
  post '/trades/edit', to: 'trades#update'
  post '/admins/edit', to: 'admins#update'


  #QUOTES
  get '/client_quotes', to: 'quotes#client_quotes'
  get '/supplier_quotes', to: 'quotes#supplier_quotes'


  #delete '/booking/:id', to: 'bookings#destroy'
  #get '/users/:id', to: 'users#show'
  #need to review this because its stopping access to user sign_in and user sign_up  , but not sure why ???
  #stopped temporarily 27.Sep.2019



  #OFFERS
  get '/offer_bookings/:id', to: 'offers#bookings', as: 'offer_bookings'
  post '/offers/:id', to: 'offers#show'
  get '/all_offers', to: 'offers#list'
  post '/offers/new', to: 'offers#create'


  ## BOOKINGS
  get '/my_bookings', to: 'bookings#my_bookings'
  get '/bookings/:id', to: 'bookings#show'
  post '/bookings', to: 'bookings#create'
  post '/booking/new', to: 'bookings#create'
  put '/bookings/:id/edit', to: 'bookings#edit'
  put '/bookings/:id/withdraw', to: 'bookings#withdraw'
  put '/bookings/:id', to: 'bookings#withdraw'
  put '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  put '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'
  get '/my_bookings', to: 'bookings#my_bookings'
  get '/bookings/:id', to: 'bookings#show'

  #REVIEWS
  post '/reviews', to: 'reviews#create'


  #LISTINGS
  get '/listings/client_listings', to: 'listings#client_listings' #listings_client_listings_path ???

  #devise_for :admins
  #devise_for :users, path: 'users'
  #devise_for :trades, path: 'trades'
  #devise_for :admins, path: 'admins'

  #get 'users/show'
  #get 'trades/show'
  #get 'admins/show'

# Devise for Users

  authenticated :users do
    # root to:'users/sessions#new', as: :authenticated_user_root
    # root to: 'users/users#dashboard', as: :authenticated_user_root
  end


  devise_for :users, path: 'users', controllers: {
      #sessions: 'users/sessions',
      # stopped calling sessions controller temporarily 21.09.19
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    },
    path_names: {
      sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'
    }

    devise_scope :users do
      get 'sign_up', :to => 'users/registrations#new'
      get 'sign_in', :to => 'users/sessions#new'
      delete 'signout', :to => 'users/sessions#destroy'
    end


    # Devise for Traders

      authenticated :trades do
       #root to:'trades/sessions#new', as: :authenticated_trade_root
       root to: 'trades/trades#dashboard', as: :authenticated_trade_root
      end


      devise_for :trades, path: 'trades', controllers: {
          sessions: 'trades/sessions',
          # stopped calling sessions controller temporarily 21.09.19
          registrations: 'trades/registrations',
          passwords: 'trades/passwords',
          confirmations: 'trades/confirmations',
          #omniauth_callbacks: 'trades/omniauth_callbacks'
        },
        path_names: {
          sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'
        }

        devise_scope :trades do
          get 'signup', :to => 'trades/registrations#new'
          get 'signin', :to => 'trades/sessions#new'
          delete 'signout', :to => 'trades/sessions#destroy'
        end

# Devise for Admins

    authenticated :admins do
      root to: 'admins/sessions#new' , as: :authenticated_admin_root
    end


    devise_for :admins, path: 'admins', controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        confirmations: 'admins/confirmations'
      }

    devise_scope :admins do
      get 'signup', :to => 'admins/registrations#new'
      get 'signin', :to => 'admins/sessions#new'
      delete 'signout', :to => 'admins/sessions#destroy'
    end

    #devise_for :users
    #  devise_scope :user do
    #  get '/users/sign_out' => 'devise/sessions#destroy'
    #end


  # resources :users, except: [:new]

  resources :users do
    #resources :address do
      resources :address_homes, controller: :address, type: 'Home'
      resources :address_business, controller: :address, type: 'Business'
      resources :address_jobs, controller: :address, type: 'Job'
      resources :address_pickups, controller: :address, type: 'PickUp'
      resources :address_dropoffs, controller: :address, type: 'DropOff'
      resources :contacts, controller: :contact
    #end
  end


  resources :trades, except: [:new]
  resources :admins, except: [:new]
  resources :categories, except: [:destroy]
  resources :sections, except: [:destroy]
  resources :pricings, except: [:destroy]
  resources :offers
  resources :bookings
  resources :after_register
  resources :after_address

  resources :listings do
    member do
      delete :delete_photo
      post :upload_photo
    end
    #resources :listing_pricings
    resources :quotes, only: [:create]      #listings/15/quotes
  end

  #resources :listing_pricings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'

end

app/views/admins/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                              <figure class="image is-128x128">
                                <%= image_tag 'icon_default_avatar.png', class:"is-rounded" %>
                              </figure>
                            </div>

                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                  <p class="title is-5"><%= current_trade.full_name %></p>
                                    <%= form_for :user, url: users_edit_url(@trade), action: :update, method: :post do |f| %>
                                    <div class="file">
                                      <label class="button is-primary is-outlined is-fullwidth">
                                        <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                        <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp;&nbsp;Upload Avatar
                                      </label>
                                    </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">

                                <!-- Member -->
                                <article class="media">
                                  <div class="media-content">Member since</div>
                                  <div class="media-right">
                                    <strong><%= current_trade.created_at.strftime('%b %Y') %></strong>
                                  </div>
                                </article>
                                <hr class="h-10">

                                <!-- From -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">From</div>
                                      <div class="media-right">
                                        <strong><%= current_trade.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                      </div>
                                    </div>
                                    <div class="content">
                                      <%= form_for :trade, url: trades_edit_url(@trade), action: :update, method: :post, html: {id: 'trade-from', class: 'is-hidden'} do |f| %>
                                      <div class="field">
                                        <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input' %>
                                      </div>
                                        <a class="toggle button is-light" aria-controls="trade-from">Cancel</a>
                                        <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">Online Status</div>
                                    <div class="media-right">
                                      <strong><% if current_trade.status %>Online <% else %> Offline <% end %></strong> <i class="toggle far fa-edit" aria-controls="trade-status"></i>
                                    </div>
                                  </div>

                                  <div class="content">
                                      <%= form_for :trade, url: trades_edit_url(@trade), action: :update, method: :post, html: {id: 'trade-status', class: 'is-hidden'} do |f| %>
                                      <div class="field">
                                        <%= f.select(:status, options_for_select([["Online", true],["Offline", false]]), {} ,{class: "select is-fullwidth"}) %>
                                      </div>
                                        <a class="toggle button is-light" aria-controls="trade-status">Cancel</a>
                                        <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>

                                </article>
                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">
                                      <P>
                                        <strong>About Yourself</strong>
                                        <br/>
                                        <%= current_trade.about %>
                                      </p>
                                    </div>
                                      <div class="media-right">
                                        <i class="toggle far fa-edit" aria-controls="trade-about"></i>
                                      </div>
                                    </div>
                                    <div class="content">
                                      <%= form_for :trade, url: trades_edit_url(@trade), action: :update, method: :post, html: {id: 'trade-about', class: 'is-hidden'} do |f| %>
                                      <div class="field">
                                        <%= f.text_field :about, autofocus: true, autocomplete: 'form', class: 'input' %>
                                      </div>
                                        <a class="toggle button is-light" aria-controls="trade-about">Cancel</a>
                                        <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Languages -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">
                                      <P>
                                        <strong>Language</strong>
                                        <br/>

                                      </p>
                                    </div>
                                      <div class="media-right">
                                        <%= current_trade.language %></strong> <i class="toggle far fa-edit" aria-controls="trade-language"></i>
                                      </div>
                                    </div>
                                    <div class="content">
                                      <%= form_for :trade, url: trades_edit_url(@trade), action: :update, method: :post, html: {id: 'trade-language', class: 'is-hidden'} do |f| %>
                                      <div class="field">
                                        <%= f.text_field :language, autofocus: true, autocomplete: 'form', class: 'input' %>
                                      </div>
                                        <a class="toggle button is-light" aria-controls="trade-language">Cancel</a>
                                        <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Linked Account -->
                                <article class="media">
                                  <div class="content">
                                    <p>
                                      <strong>Linked Account</strong><br/>

                                        <% if current_trade.uid %>
                                          <span class="has-text-success">Facebook Verified</span>
                                        <% else %>
                                          <%= link_to 'Connect to Facebook', user_facebook_omniauth_authorize_path, class: "has-text-danger" %>
                                        <% end %>


                                      </p>
                                  </div>
                                </article>

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Gig -->
                    <div class="column is-one-third has-text-centered"></div>

                    <!-- Sample Gig -->
                    <div class="column is-one-third has-text-centered"></div>

                </div>
            </div>

        </div>
    </div>
</section>

app/views/admins/index.html.erb
<div class="container tn_top_bottom_spacer">
    <h3 align="center"> Servizio Admin Users</h3>
    <div align="center">
            <% @admin.each do |admin| %>
              <ul class = "user-listing">
                      <div class="row">
                            <div class="col-md-4">
                                        <li><%= image_tag admin_avatar(admin, 150), class: "rounded-circle mx-auto d-block" %><li>
                                                <li class="listing-title">
                                                  <%= link_to admin.username, admin_path(admin) %>
                                                </li>
                            </div>


                        </div>
                </ul>
        <% end %>
            <div class="digg_pagination">
              <div align="center">
                  <div class="page_info">
                    <%= page_entries_info @admin %>
                  </div>
                    <%= will_paginate @admin  %>
                  </div>
            </div>

    </div>
</div>

app/views/admins/show.html.erb
<div class="container tn_top_bottom_spacer">

<h3 align="center">Welcome to <%= @admin.username %>'s page</h3>

<div class="row">
  <div class="col-md-12">
    <%= image_tag admin_avatar(@admin, 150), class: "rounded-circle mx-auto d-block" %>
  </div>
</div>
<br />
<h4 align="center"><%= @admin.username %>'s listings</h4>

</div>